openapi: 3.0.4
info:
  title: Blackbird AEM Connector –  OpenAPI 3.0
  version: 1.0.0
  description: >
    API endpoints for blackbird aem connector for interacting with an AEM environment

tags:
  - name: Content
    description: Process Structured JCR Content

paths:
  /content/services/bb-aem-connector/content.json:
    get:
      tags:
        - Content
      summary: Get structured JCR content from a given resource path
      description: |
        This endpoint returns structured JCR nodes and their properties as JSON.

        - The URL **must end with `.json`** to trigger AEM servlet resolution and JSON rendering.
        - The `contentPath` is a required query parameter representing the JCR path to the root node.
        - If no content path is provided, a **400 Bad Request** is returned.
        - If the specified content path cannot be resolved in the JCR, a **404 Not Found** is returned.

        Examples:
        `/content/services/bb-aem-connector/content.json?contentPath=/content/bb-aem-connector/us/en`
        `/content/services/bb-aem-connector/content.json?contentPath=/content/mysite/page/jcr:content`
      parameters:
        - in: query
          name: contentPath
          required: true
          description: >
            The JCR path to read, passed as a suffix. Must start with a `/`.
          schema:
            type: string
            example: /content/bb-aem-connector/us/en
      responses:
        '200':
          description: Structured content for the specified JCR path
          content:
            application/json:
              schema:
                type: object
                properties:
                  values:
                    type: array
                    items:
                      $ref: '#/components/schemas/BlackbirdJcrNode'
              examples:
                ExampleResponse:
                  summary: Example structured response
                  value:
                    values:
                      - name: jcr:content
                        path: /content/bb-aem-connector/us/en/search/jcr:content
                        properties:
                          - name: jcr:primaryType
                            value: cq:PageContent
                            multiValue: false
                          - name: jcr:createdBy
                            value: admin
                            multiValue: false
                          - name: cq:allowedTemplates
                            values:
                              - /conf/bb-aem-connector/settings/wcm/templates/(?!(landing|root)).*
                            multiValue: true
        '400':
          description: Bad Request – Missing required query parameter contentPath
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdErrorResponse'
        '404':
          description: Not Found – Content Not found for path
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdErrorResponse'

  /content/services/bb-aem-connector/pages/events.json:
    get:
      tags:
        - Page Events Viewer
      summary: Info about pages that were created or modified during a definite period of time.
      description: |
        Info about pages that were created or modified during a definite period of time.
        Examples:
                `/content/services/bb-aem-connector/pages/events?rootPath=/content/bb-aem-connector&startDate=2025-03-24&endDate=2025-03-26&offset=3limit=5&events=modified&events=created`
      parameters:
        - in: query
          name: rootPath
          description: The path under which pages are searched.
          schema:
            type: string
            example: /content/my-site
        - in: query
          name: startDate
          required: true
          description: Start date for filtering events (in ISO8601 format YYYY-MM-DDTHH:mm:ss.SSSZ or partial representations, like YYYY-MM-DD)
          schema:
            type: string
            example: 2025-03-15
        - in: query
          name: endDate
          required: true
          description: End date for filtering events (in ISO8601 format YYYY-MM-DDTHH:mm:ss.SSSZ or partial representations, like YYYY-MM-DD).
          schema:
            type: string
            example: 2025-03-31
        - in: query
          name: offset
          required: false
          description: Offset for pagination. Defaults to 0.
          schema:
            type: integer
            default: 0
        - in: query
          name: limit
          required: false
          description: Limit for pagination. Defaults to -1 (no limit).
          schema:
            type: integer
            default: -1
        - in: query
          name: events
          required: false
          description: A list of event types to filter. Multiple values can be provided.
          schema:
            type: array
            items:
              type: string
            example: [ "created", "modified" ]

      responses:
        '200':
          description: A json object representing the page event viewer data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdPageEventViewerDto'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdErrorResponse'
        '500':
          description: Internal Server Error - an error occurred while processing the request
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/BlackbirdErrorResponse'
  /content/services/bb-aem-connector/page-exporter.json:
    get:
      tags:
        - Page Exporter
      summary: Export AEM Page Content
      description: |
        This API endpoint exports the content of an AEM page in JSON format. It serializes the page content recursively, filtering out blacklisted properties
        and nodes based on the configured BlackbirdPageContentFilterService.
        Examples: 
              `/content/services/bb-aem-connector/page-exporter.json?pagePath=/content/wknd/language-masters/en/adventures/ski-touring-mont-blanc`
      parameters:
        - in: query
          name: pagePath
          required: true
          description: The absolute JCR path of the page to export. Must be an absolute path starting with '/'.
          schema:
            type: string
            example: /content/wknd/language-masters/en/adventures/ski-touring-mont-blanc

      responses:
        '200':
          description: Successful page export.
          content:
            application/json:
              schema:
                type: object
                description: JSON representation of the page content.
                additionalProperties: true
        '400':
          description: >
            Bad Request - Either the "pagePath" query parameter is missing, the path does not start with '/',
            or the resource does not represent a valid CQ page.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdErrorResponse'
        '404':
          description: >
            Not Found - The resource for the given "pagePath" was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdErrorResponse'
        '409':
          description: >
            Conflict - The page exists but does not have a "jcr:content" node.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdErrorResponse'
  /content/services/bb-aem-connector/page-importer.json:
    post:
      tags:
        - Page Importer
      summary: Import a Page with Merged Content
      description: >
        Copies an existing page from a given source path, merges the page with the provided JSON content, 
        and creates or updates a page at the target path.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sourcePath
                - targetPath
                - targetContent
              properties:
                sourcePath:
                  type: string
                  description: Absolute path of the source page to be copied.
                  example: "/content/bb-aem-connector/us/en/products/category-page"
                targetPath:
                  type: string
                  description: Absolute path for the destination or target page.
                  example: "/content/bb-aem-connector/pl/pl/products/category-page"
                targetContent:
                  type: object
                  description: >
                    An object containing the target content to be merged into the copied page.
                    This must be a valid JSON object and repeat the structure of the source page.
                  example:
                    jcr:content:
                      jcr:title: "Strona kategorii"
                      text: "Witamy w hotelu California"
                      root:
                        container:
                          container:
                            months:
                              - "Marzec"
                              - "Kwiecień"
                              - "Maj"
      responses:
        '200':
          description: Page imported successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Page imported successfully"
                  path:
                    type: string
                    example: "/content/bb-aem-connector/pl/pl/products/category-page"
        '400':
          description: Bad Request – Missing required fields or invalid payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdErrorResponse'
        '401':
          description: Unauthorized – Login exception encountered.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdErrorResponse'
        '500':
          description: Internal Server Error – An error occurred during the import process.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdErrorResponse'
components:
  schemas:
    BlackbirdJcrNode:
      type: object
      description: |
        Represents a JCR node with its name, full path, and a list of content properties.
        - Typically represents nodes like `jcr:content` or pages under a given content path.
      properties:
        name:
          type: string
          description: Name of the JCR node (e.g. "jcr:content")
        path:
          type: string
          description: Full path to the node in the JCR repository (e.g. "/content/site/page/jcr:content")
        properties:
          type: array
          description: List of serialized properties associated with this node.
          items:
            $ref: '#/components/schemas/BlackbirdJcrProperty'

    BlackbirdJcrProperty:
      type: object
      description: |
        Represents a single property from a JCR node.
        Skips empty values, so a property can either be single-valued or multi-valued depending on the use case.
        - Use `value` for single-value properties
        - Use `values` for multi-value properties
        - The `multiValue` field indicates which mode is used
      properties:
        name:
          type: string
          description: The name of the JCR property (e.g. "jcr:title", "cq:tags")
        value:
          type: string
          description: The property's single value. Present only when `multiValue` is `false`.
        values:
          type: array
          description: A list of values if the property is multi-valued.
          items:
            type: string
        multiValue:
          type: boolean
          description: Indicates whether the property has multiple values

    BlackbirdPageEventViewerDto:
      type: object
      description: Represents the response data for a page events search.
      properties:
        rootPath:
          type: string
          description: The JCR root path used for the search.
          example: /content/my-site
        startDate:
          type: string
          description: The start date for filtering events.
          example: 2025-03-01
        endDate:
          type: string
          description: The end date for filtering events.
          example: 2025-03-05
        offset:
          type: integer
          description: The pagination offset.
          example: 0
        limit:
          type: integer
          description: The pagination limit.
          example: 8
        events:
          type: array
          description: A list of event types that were used for filtering.
          items:
            type: string
          example: [ "created" ]
        totalMatches:
          type: integer
          description: Total number of matching pages.
          example: 100
        hasMore:
          type: boolean
          description: Indicates if there are more pages beyond the total matches.
          example: false
        results:
          type: integer
          description: The number of results returned.
          example: 10
        pages:
          type: array
          description: A list of pages.
          items:
            $ref: '#/components/schemas/BlackbirdEventViewerPage'

    BlackbirdEventViewerPage:
      type: object
      description: Represents a page for Page Event Viewer servlet
      properties:
        title:
          type: string
          description: page title
          example: Home Page
        path:
          type: string
          description: page path
          example: /content/my-site/home
        created:
          type: string
          description: the date pages was created
          example: 2025-03-15
        modified:
          type: string
          description: the date page was modified
          example: 2025-03-20

    BlackbirdErrorResponse:
      type: object
      description: Represents an error response.
      properties:
        status:
          type: integer
          description: HTTP status code.
          example: 400
        error:
          type: string
          description: Short error description.
          example: "Bad Request"
        message:
          type: string
          description: Detailed error message.
          example: "Invalid request parameters"
        path:
          type: string
          description: The request path that resulted in the error.
          example: "/content/services/bb-aem-connector/pages/events"
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the error in yyyy-MM-dd HH:mm:ss format (UTC).
          example: "2025-03-31 12:34:56"