openapi: 3.0.4
info:
  title: Blackbird AEM Connector –  OpenAPI 3.0
  version: 1.0.0
  description: >
    API endpoints for blackbird aem connector for interacting with an AEM environment

tags:
  - name: Content
    description: Process Structured JCR Content

paths:
  /content/services/bb-aem-connector/content.json{contentPath}:
    get:
      tags:
        - Content
      summary: Get structured JCR content from a given resource path
      description: |
        This endpoint returns structured JCR nodes and their properties as JSON.

        - The URL **must end with `.json`** to trigger AEM servlet resolution and JSON rendering.
        - The `{contentPath}` is a required suffix representing the JCR path to the root node.
        - If no content path is provided, a **400 Bad Request** is returned.
        - If the specified content path cannot be resolved in the JCR, a **404 Not Found** is returned.

        Examples:
        `/content/services/bb-aem-connector/content.json/content/bb-aem-connector/us/en`
        `/content/services/bb-aem-connector/content.json/content/mysite/page/jcr:content`
      parameters:
        - name: contentPath
          in: path
          required: true
          description: >
            The JCR path to read, passed as a suffix. Must start with a `/`.
          schema:
            type: string
            example: /content/bb-aem-connector/us/en
      responses:
        '200':
          description: Structured content for the specified JCR path
          content:
            application/json:
              schema:
                type: object
                properties:
                  values:
                    type: array
                    items:
                      $ref: '#/components/schemas/BlackbirdJcrNode'
              examples:
                ExampleResponse:
                  summary: Example structured response
                  value:
                    values:
                      - name: jcr:content
                        path: /content/bb-aem-connector/us/en/search/jcr:content
                        properties:
                          - name: jcr:primaryType
                            value: cq:PageContent
                            multiValue: false
                          - name: jcr:createdBy
                            value: admin
                            multiValue: false
                          - name: cq:allowedTemplates
                            values:
                              - /conf/bb-aem-connector/settings/wcm/templates/(?!(landing|root)).*
                            multiValue: true
        '400':
          description: Bad Request – missing content path
        '404':
          description: Not Found – JCR path in contentPath could not be resolved

  /services/bb-aem-connector/pages/events.json:
    get:
      tags:
        - Page Events Viewer
      summary: Info about pages that were created or modified during a definite period of time.
      description: |
        Info about pages that were created or modified during a definite period of time.
        Examples:
                `/content/services/bb-aem-connector/pages/events?rootPath=/content/bb-aem-connector&startDate=2025-03-24&endDate=2025-03-26&offset=3limit=5&events=modified&events=created`
      parameters:
        - in: query
          name: rootPath
          description: The path under which pages are searched.
          schema:
            type: string
            example: /content/my-site
        - in: query
          name: startDate
          required: true
          description: Start date for filtering events (in ISO8601 format YYYY-MM-DDTHH:mm:ss.SSSZ or partial representations, like YYYY-MM-DD)
          schema:
            type: string
            example: 2025-03-15
        - in: query
          name: endDate
          required: true
          description: End date for filtering events (in ISO8601 format YYYY-MM-DDTHH:mm:ss.SSSZ or partial representations, like YYYY-MM-DD).
          schema:
            type: string
            example: 2025-03-31
        - in: query
          name: offset
          required: false
          description: Offset for pagination. Defaults to 0.
          schema:
            type: integer
            default: 0
        - in: query
          name: limit
          required: false
          description: Limit for pagination. Defaults to -1 (no limit).
          schema:
            type: integer
            default: -1
        - in: query
          name: events
          required: false
          description: A list of event types to filter. Multiple values can be provided.
          schema:
            type: array
            items:
              type: string
            example: [ "created", "modified" ]

      responses:
        '200':
          description: A json object representing the page event viewer data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdPageEventViewerDta'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlackbirdErrorResponse'
        '500':
          description: Internal Server Error - an error occurred while processing the request
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/BlackbirdErrorResponse'

components:
  schemas:
    BlackbirdJcrNode:
      type: object
      description: |
        Represents a JCR node with its name, full path, and a list of content properties.
        - Typically represents nodes like `jcr:content` or pages under a given content path.
      properties:
        name:
          type: string
          description: Name of the JCR node (e.g. "jcr:content")
        path:
          type: string
          description: Full path to the node in the JCR repository (e.g. "/content/site/page/jcr:content")
        properties:
          type: array
          description: List of serialized properties associated with this node.
          items:
            $ref: '#/components/schemas/BlackbirdJcrProperty'

    BlackbirdJcrProperty:
      type: object
      description: |
        Represents a single property from a JCR node.
        Skips empty values, so a property can either be single-valued or multi-valued depending on the use case.
        - Use `value` for single-value properties
        - Use `values` for multi-value properties
        - The `multiValue` field indicates which mode is used
      properties:
        name:
          type: string
          description: The name of the JCR property (e.g. "jcr:title", "cq:tags")
        value:
          type: string
          description: The property's single value. Present only when `multiValue` is `false`.
        values:
          type: array
          description: A list of values if the property is multi-valued.
          items:
            type: string
        multiValue:
          type: boolean
          description: Indicates whether the property has multiple values

    BlackbirdPageEventViewerDto:
      type: object
      description: Represents the response data for a page events search.
      properties:
        rootPath:
          type: string
          description: The JCR root path used for the search.
          example: /content/my-site
        startDate:
          type: string
          description: The start date for filtering events.
          example: 2025-03-01
        endDate:
          type: string
          description: The end date for filtering events.
          example: 2025-03-05
        offset:
          type: integer
          description: The pagination offset.
          example: 0
        limit:
          type: integer
          description: The pagination limit.
          example: 8
        events:
          type: array
          description: A list of event types that were used for filtering.
          items:
            type: string
          example: [ "created" ]
        totalMatches:
          type: integer
          description: Total number of matching pages.
          example: 100
        hasMore:
          type: boolean
          description: Indicates if there are more pages beyond the total matches.
          example: false
        results:
          type: integer
          description: The number of results returned.
          example: 10
        pages:
          type: array
          description: A list of pages.
          items:
            $ref: '#/components/schemas/BlackbirdEventViewerPage'

    BlackbirdEventViewerPage:
      type: object
      description: Represents a page for Page Event Viewer servlet
      properties:
        title:
          type: string
          description: page title
          example: Home Page
        path:
          type: string
          description: page path
          example: /content/my-site/home
        created:
          type: string
          description: the date pages was created
          example: 2025-03-15
        modified:
          type: string
          description: the date page was modified
          example: 2025-03-20

    BlackbirdErrorResponse:
      type: object
      description: Represents an error response.
      properties:
        status:
          type: integer
          description: HTTP status code.
          example: 400
        error:
          type: string
          description: Short error description.
          example: "Bad Request"
        message:
          type: string
          description: Detailed error message.
          example: "Invalid request parameters"
        path:
          type: string
          description: The request path that resulted in the error.
          example: "/content/services/bb-aem-connector/pages/events"
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the error in yyyy-MM-dd HH:mm:ss format (UTC).
          example: "2025-03-31 12:34:56"